import { create } from "zustand";

interface IProfileData{
    id: number | null,
    first_name: string,
    last_name: string,
    gender: string, 
    birthday: string, 
    dating_purpose: string, 
    searching_gender: string, 
    description: string, 
    smokes_cigarettes: boolean | null, 
    drinks_alcoholics: boolean | null, 
    zodiac_signs: string, 
    education: string, 
    job: string, 
    age: number | null, 
    is_active: boolean | null,
}

interface IProfileStore{
    id: number | null,
    first_name: string,
    last_name: string,
    gender: string, 
    birthday: string, 
    dating_purpose: string, 
    searching_gender: string, 
    description: string, 
    smokes_cigarettes: boolean | null, 
    drinks_alcoholics: boolean | null, 
    zodiac_signs: string, 
    education: string, 
    job: string, 
    age: number | null, 
    is_active: boolean | null,
    // actions
    setId: (newId: number) => void,
    setFirstName: (newFirstName: string) => void,
    setLastName: (newLastName: string) => void,
    setGender: (newGender: string) => void, 
    setBirthday: (newBirhday: string) => void, 
    setDatingPurpose: (newDatingPurpose: string) => void, 
    setSearchingGender: (newSearchingGender: string) => void, 
    setDescription: (newDescription: string) => void, 
    setSmokesCigarettes: (bool: boolean) => void, 
    setDrinksAlcoholics: (bool: boolean) => void, 
    setZodiacSigns: (newZodiacSigns: string) => void, 
    setEducation: (newEducation: string) => void, 
    setJob: (newJob: string) => void, 
    setAge: (newAge: number) => void, 
    setIsActive: (bool: boolean) => void,
    setAll: (profileData: IProfileData) => void
}

export const useProfileStore = create<IProfileStore>((set) => ({
    id: null,
    first_name: "",
    last_name: "",
    gender: "", 
    birthday: "", 
    dating_purpose: "", 
    searching_gender: "", 
    description: "", 
    smokes_cigarettes: null, 
    drinks_alcoholics: null, 
    zodiac_signs: "", 
    education: "", 
    job: "", 
    age: null, 
    is_active: null, 

    setId: (newId) => set({id: newId}),
    setFirstName: (newFirstName) => set({first_name: newFirstName}),
    setLastName: (newLastName) => set({last_name: newLastName}),
    setGender: (newGender) => set({gender: newGender}), 
    setBirthday: (newBirhday) => set({birthday: newBirhday}), 
    setDatingPurpose: (newDatingPurpose) => set({dating_purpose: newDatingPurpose}), 
    setSearchingGender: (newSearchingGender) => set({searching_gender: newSearchingGender}), 
    setDescription: (newDescription) => set({description: newDescription}), 
    setSmokesCigarettes: (bool) => set({smokes_cigarettes: bool}), 
    setDrinksAlcoholics: (bool) => set({drinks_alcoholics: bool}), 
    setZodiacSigns: (newZodiacSigns) => set({zodiac_signs: newZodiacSigns}), 
    setEducation: (newEducation) => set({education: newEducation}), 
    setJob: (newJob) => set({job: newJob}), 
    setAge: (newAge) => set({age: newAge}), 
    setIsActive: (bool) => set({is_active: bool}),

    setAll: (profileData) => set({...profileData})
}))